### ISSUE TITLE
GitHub style markdown

### ISSUE THREAD

**Issue by joshferrell** [elmasse/hyper-markdown-preview#3]
It would be cool to render the markdown using GitHub's style of markdown using a config option setting.

For example, the code blocks on GitHub use a light grey background.

Example config settings:
```
module.exports = {
  config: {
    ...
      hyperMarkdown: {
        markdownStyle: 'GitHub', // Can be one of (default, Bitbucket, or GitHub)
      }
    ...
  }
}
```

**Comment by elmasse** [comment]
Hi @joshferrell yes, I was thinking about this, never implemented since the plugin was not being used so much :(. I'll give it a try today or tomorrow, I guess adding github stylesheets will be simple. I have to do some more research on using others (bitbucket, gitlab, etc).
Maybe another interesting feature in that direction will be to detect if the md file directory is a repo and then apply the right stylesheet. Not sure thou about that yet.


Thanks for this suggestion! And if you want to contribute I'm open to review any PR.
